### ISSUE TITLE
Broken link to attribute grammars

### ISSUE THREAD

**Issue by kinow** [pavpanchekha/emberfox#101]
Hi,

In https://browser.engineering/layout.html, there's a note-box about attribute grammars with a broken link to https://browser.engineering/wiki-atgram

Maybe it was supposed to link https://en.wikipedia.org/wiki/Attribute_grammar? (from the `wiki` part in the link?)

Thanks!
Bruno

**Comment by pavpanchekha** [comment]
Fixed in commit acbdbfc
