### ISSUE TITLE
Link to home on every page

### ISSUE THREAD

**Issue by abrhim** [pavpanchekha/emberfox#91]
As noted on this page: https://browser.engineering/preface.html there is no UI given to navigate back to the home page of the book. If one is reading a chapter and navigates multiple pages into the book using the given buttons, it would require multiple presses of a browser's back button to finally come back to the home page.

**Comment by pavpanchekha** [comment]
The gray nav bar at the top / bottom of each page links to the WBE homepage. I'll consider how to make that more prominent when I next pass over the design.
