### ISSUE TITLE
Dead-ish link to tkinter canvas documentation

### ISSUE THREAD

**Issue by DanielRosenwasser** [pavpanchekha/emberfox#93]
The [Graphics Chapter](https://github.com/pavpanchekha/emberfox/blob/48551f4fd927b979975e3db7404ac3db22fa03b3/book/graphics.md) has a link to http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/canvas.html which seems to time out now. Is there another resource or a mirror that could be used instead?

**Comment by pavpanchekha** [comment]
Replaced with a mirror link. This one's on Github and hopefully will stay alive longer...?
